// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;



namespace MediHawker.Data
{
    public partial class MedihawkerDbContext : DbContext
    {
        public MedihawkerDbContext()
        {
        }

        public MedihawkerDbContext(DbContextOptions<MedihawkerDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ConConsumers> ConConsumers { get; set; }
        public virtual DbSet<ConConsumersDetails> ConConsumersDetails { get; set; }
        public virtual DbSet<ConConsumersPurchaseHistory> ConConsumersPurchaseHistory { get; set; }
        public virtual DbSet<ConOrderDetails> ConOrderDetails { get; set; }
        public virtual DbSet<ConOrders> ConOrders { get; set; }
        public virtual DbSet<ConProducts> ConProducts { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            

            

           

            





            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}