// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MediHawker.Data
{
    public partial class Cart
    {
        public int Id { get; set; }
        public int CartItemId { get; set; }
        public int ProductId { get; set; }
        public int ConsumerId { get; set; }
        public int ProductCount { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal TotalPrice { get; set; }
    }
}