// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace MediHawker.Data
{
    public partial class ConConsumers
    {
        public int ConsumerId { get; set; }
        public string UserName { get; set; }
        public string CartItemCount { get; set; }
        public string Phone { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? CreatedBy { get; set; }
    }
}