// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace MediHawker.Data
{
    public partial class ConProducts
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string GenericName { get; set; }
        public string PaxCount { get; set; }
        public int? ManufacturerId { get; set; }
        public int? Dose { get; set; }
        public double? UnitPrice { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? CreatedBy { get; set; }
    }
}