// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace MediHawker.Data
{
    public partial class ConsumersDetails
    {
        public int ConsumerDetailsId { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }


        //remove nullable
        public int? ConsumerId { get; set; }


        public DateTime CreatedOn { get; set; }
        public int? CreatedBy { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}