// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace MediHawker.Data
{
    public partial class ConsumersPurchaseHistory
    {
        public int PurchaseHistoryId { get; set; }
        public int? ConsumerId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? CreatedBy { get; set; }
        public int? OrderId { get; set; }
    }
}