// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace MediHawker.Data
{
    public partial class Products
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string GenericName { get; set; }
        public int? PaxCount { get; set; }
        public int? ManufacturerId { get; set; }
        public int? Dose { get; set; }
        public double? UnitPrice { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? CreatedBy { get; set; }
        public decimal BuyingPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public string Address { get; set; }
        public string ImgPath { get; set; }
        public int? GenericId { get; set; }
        public string Description { get; set; }
    }
}